FROM node:18-alpine

# Install dependencies
RUN apk add --no-cache nginx

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Copy .env file to build directory
COPY .env ./build/

# Install dependencies in build directory
WORKDIR /app/build
RUN npm i

# Create nginx configuration
WORKDIR /app
RUN mkdir -p /etc/nginx/conf.d
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose ports
EXPOSE 80 3333

# Start Nginx and Node.js application
CMD sh -c "nginx && node build/bin/server.js"
