FROM node:22-alpine

# Installe nginx
RUN apk add --no-cache nginx

# Prépare le dossier
WORKDIR /app

# Copie et installe les dépendances pour le build
COPY package*.json ./
RUN npm ci

# Copie le reste
COPY . .

# Build de l'app (React ou Adonis)
RUN npm run build

# Copie l'ENV de prod dans le dossier build si besoin
COPY .env ./build/

# Installe uniquement les dépendances de prod
WORKDIR /app/build
RUN npm ci --omit=dev

# Reviens à la racine
WORKDIR /app

# Prépare la conf nginx
RUN mkdir -p /etc/nginx/conf.d
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copie le start.sh et rends-le exécutable
COPY docker/start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Utilise CMD proprement
CMD ["/app/start.sh"]
